using System;
using System.Collections.Generic;
using System.Text;
using BookShop.Dal.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

//Ati: Ezekben a konfigurációs fájlokban töltjük fel az adatbázisunkat tesztadatokkal.

namespace BookShop.Dal.EntityConfiguration
{
    public class AuthorEntityConfiguration : IEntityTypeConfiguration<Author>
    {
        public void Configure(EntityTypeBuilder<Author> builder)
        {
            builder.HasData(
                new Author { Id = 1,   DisplayName = "Lam Kam Chuen Mester" },
                new Author { Id = 2,   DisplayName = "Susanne Schumacher" },
                new Author { Id = 3,   DisplayName = "Ernest J.Eitel" },
                new Author { Id = 4,   DisplayName = "Simon Brown" },
                new Author { Id = 5,   DisplayName = "François Villon" },
                new Author { Id = 6,   DisplayName = "Sándor László, Pocsai Katalin" },
                new Author { Id = 7,   DisplayName = "Raymond Lo" },
                new Author { Id = 8,   DisplayName = "Jes T.Y.Lim" },
                new Author { Id = 9,   DisplayName = "Fekete Zoltán, Zalay Miklós" },
                new Author { Id = 10,  DisplayName = "Gill Hale, Mark Evans" },
                new Author { Id = 11,  DisplayName = "Szilvásy Judit" },
                new Author { Id = 12,  DisplayName = "Stanislav Grof, Christina Grof" },
                new Author { Id = 13,  DisplayName = "Judy Allen" },
                new Author { Id = 14,  DisplayName = "Jhampa Shaneman, Jan V.Angel" },
                new Author { Id = 15,  DisplayName = "Horváth Andrea" },
                new Author { Id = 16,  DisplayName = "Claus Reimann" },
                new Author { Id = 17,  DisplayName = "Tomasz Lem" },
                new Author { Id = 18,  DisplayName = "Tai San" },
                new Author { Id = 19,  DisplayName = "Robert Powell" },
                new Author { Id = 20,  DisplayName = "Bakos Attila" },
                new Author { Id = 21,  DisplayName = "Julia Parker, Derek Parker" },
                new Author { Id = 22,  DisplayName = "Kalo Jenő" },
                new Author { Id = 23,  DisplayName = "Buji Ferenc" },
                new Author { Id = 24,  DisplayName = "Késmárki László" },
                new Author { Id = 25,  DisplayName = "Koffi Kwahulé" },
                new Author { Id = 26,  DisplayName = "Madách Imre" },
                new Author { Id = 27,  DisplayName = "Spiró György" },
                new Author { Id = 28,  DisplayName = "Isa Schneider" },
                new Author { Id = 29,  DisplayName = "Solara" },
                new Author { Id = 30,  DisplayName = "Alfred Jarry" },
                new Author { Id = 31,  DisplayName = "Faludy György" },
                new Author { Id = 32,  DisplayName = "Paulinyi Tamás" },
                new Author { Id = 33,  DisplayName = "Brian Haughton" },
                new Author { Id = 34,  DisplayName = "Ronald H.Hulnick, Mary R.Hulnick" },
                new Author { Id = 35,  DisplayName = "José ifj.Silva, Ed ifj.Bernd" },
                new Author { Id = 36,  DisplayName = "Lou Aronica, Ken, Sir Robinson" },
                new Author { Id = 37,  DisplayName = "Charles T.Tart" },
                new Author { Id = 38,  DisplayName = "Lisa Rogak" },
                new Author { Id = 39,  DisplayName = "Kornis Mihály" },
                new Author { Id = 40,  DisplayName = "Börcsök László" },
                new Author { Id = 41,  DisplayName = "Veszprémi Tamás" },
                new Author { Id = 42,  DisplayName = "Pierre Merle" },
                new Author { Id = 43,  DisplayName = "Komáromi Gabriella" },
                new Author { Id = 44,  DisplayName = "Ingmar Bergman" },
                new Author { Id = 45,  DisplayName = "Oliver Sacks" },
                new Author { Id = 46,  DisplayName = "Ámosz Oz" },
                new Author { Id = 47,  DisplayName = "Alexander Brody" },
                new Author { Id = 48,  DisplayName = "Cecilie Loveid" },
                new Author { Id = 49,  DisplayName = "Jon Fosse" },
                new Author { Id = 50,  DisplayName = "Alighieri Dante" },
                new Author { Id = 51,  DisplayName = "Arthur Miller" },
                new Author { Id = 52,  DisplayName = "dr.Popper Péter" },
                new Author { Id = 53,  DisplayName = "Tom Bryan" },
                new Author { Id = 54,  DisplayName = "Röhrig Géza" },
                new Author { Id = 55,  DisplayName = "William Shakespeare" },
                new Author { Id = 56,  DisplayName = "Dsida Jenő" },
                new Author { Id = 57,  DisplayName = "Arany János" },
                new Author { Id = 58,  DisplayName = "Andrási Tiborné, Czeglédy István, dr.Czeglédy Istvánné" },
                new Author { Id = 59,  DisplayName = "Berkes Klára" },
                new Author { Id = 60,  DisplayName = "Tony Crilly" },
                new Author { Id = 61,  DisplayName = "Stuart Clark" },
                new Author { Id = 62,  DisplayName = "Katona Gyula Y., Recski András, Szabó Csaba" },
                new Author { Id = 63,  DisplayName = "Obádovics J.Gyula" },
                new Author { Id = 64,  DisplayName = "Halász Ágnes" },
                new Author { Id = 65,  DisplayName = "Theodore Gray" },
                new Author { Id = 66,  DisplayName = "Lente Gábor, Kovács Lajos, Gunda Tamás, Csupor Dezső" },
                new Author { Id = 67,  DisplayName = "Kremmer Tibor, Torkos Kornél" },
                new Author { Id = 68,  DisplayName = "Adam Smith" },
                new Author { Id = 69,  DisplayName = "Zugorné Rácz Éva" },
                new Author { Id = 70,  DisplayName = "Stefan Kassay" },
                new Author { Id = 71,  DisplayName = "Kornai János" },
                new Author { Id = 72,  DisplayName = "Galbács Péter" },
                new Author { Id = 73,  DisplayName = "Simon Bishop, Mike Walker" },
                new Author { Id = 74,  DisplayName = "Csáki György" },
                new Author { Id = 75,  DisplayName = "N.Gregory Mankiw" },
                new Author { Id = 76,  DisplayName = "Kopátsy Sándor" },
                new Author { Id = 77,  DisplayName = "Csurgó Sándor" },
                new Author { Id = 78,  DisplayName = "Dóry Béla" },
                new Author { Id = 79,  DisplayName = "Enzo Gallori" },
                new Author { Id = 80,  DisplayName = "Tóth Gábor" },
                new Author { Id = 81,  DisplayName = "Vajta Gábor" },
                new Author { Id = 82,  DisplayName = "I.N.Smeretle" },
                new Author { Id = 83,  DisplayName = "Monika Offenberger" },
                new Author { Id = 84,  DisplayName = "Sarah, dr.Brewer" },
                new Author { Id = 85,  DisplayName = "Róbert Ceman" },
                new Author { Id = 86,  DisplayName = "Ljudmila Ulickaja" },
                new Author { Id = 87,  DisplayName = "Fábián Janka" },
                new Author { Id = 88,  DisplayName = "Jonathan Safran Foer" },
                new Author { Id = 89,  DisplayName = "Elif Shafak" },
                new Author { Id = 90,  DisplayName = "Singer Arje Iván" },
                new Author { Id = 91,  DisplayName = "Büky Anna" },
                new Author { Id = 92,  DisplayName = "Vlagyimir Szorokin" },
                new Author { Id = 93,  DisplayName = "Steven Erikson" },
                new Author { Id = 94,  DisplayName = "J.R.R.Tolkien" },
                new Author { Id = 95,  DisplayName = "Raymond E.Feist, Steve Stirling" },
                new Author { Id = 96,  DisplayName = "George R.R.Martin" },
                new Author { Id = 97,  DisplayName = "Kövesi Péter" },
                new Author { Id = 98,  DisplayName = "R.A.Salvatore" },
                new Author { Id = 99,  DisplayName = "Raymond E.Feist" },
                new Author { Id = 100, DisplayName = "Szappanos Gábor" },
                new Author { Id = 101, DisplayName = "Király - Acampora Anikó" },
                new Author { Id = 102, DisplayName = "Egon Erwin Kisch" },
                new Author { Id = 103, DisplayName = "Szendrődy Szonja" },
                new Author { Id = 104, DisplayName = "Kresley Cole" },
                new Author { Id = 105, DisplayName = "Bertrice Small" },
                new Author { Id = 106, DisplayName = "Julius J.Coach" },
                new Author { Id = 107, DisplayName = "Pedro Almodóvar" },
                new Author { Id = 108, DisplayName = "Cathryn Cooper" },
                new Author { Id = 109, DisplayName = "Carlos Ruiz Zafón" },
                new Author { Id = 110, DisplayName = "Stieg Larsson" },
                new Author { Id = 111, DisplayName = "Szalai Vivien" },
                new Author { Id = 112, DisplayName = "George P.Pelecanos" },
                new Author { Id = 113, DisplayName = "Joanne Fluke" },
                new Author { Id = 114, DisplayName = "Gerritsen Tess" },
                new Author { Id = 115, DisplayName = "Arthur Bernéde" },
                new Author { Id = 116, DisplayName = "Ross Macdonald" },
                new Author { Id = 117, DisplayName = "Bernard Knight" },
                new Author { Id = 118, DisplayName = "Agatha Christie" },
                new Author { Id = 119, DisplayName = "Linda Castillo" },
                new Author { Id = 120, DisplayName = "Martin Delrio" },
                new Author { Id = 121, DisplayName = "Philip K.Dick" },
                new Author { Id = 122, DisplayName = "Alan E.Nourse, William S.Burroughs" },
                new Author { Id = 123, DisplayName = "Robert Charles Wilson" },
                new Author { Id = 124, DisplayName = "Arkagyij Sztrugackij, Borisz Sztrugackij" },
                new Author { Id = 125, DisplayName = "Arthur C.Clarke, Stephen Baxter" },
                new Author { Id = 126, DisplayName = "Szergej Lukjanyenko" },
                new Author { Id = 127, DisplayName = "Frank Herbert" },
                new Author { Id = 128, DisplayName = "Nathan Archer" },
                new Author { Id = 129, DisplayName = "Lisa Jackson" },
                new Author { Id = 130, DisplayName = "Jónás Zsolt" },
                new Author { Id = 131, DisplayName = "Joe Hill" },
                new Author { Id = 132, DisplayName = "Bíró Szabolcs" },
                new Author { Id = 133, DisplayName = "Kathy Reichs" },
                new Author { Id = 134, DisplayName = "Steve Berry" },
                new Author { Id = 135, DisplayName = "Zima Szabolcs" },
                new Author { Id = 136, DisplayName = "Frei Tamás" },
                new Author { Id = 137, DisplayName = "Árpa Attila" },
                new Author { Id = 138, DisplayName = "Sam Barone" },
                new Author { Id = 139, DisplayName = "Andrew Sanders" },
                new Author { Id = 140, DisplayName = "Tracy Chevalier" },
                new Author { Id = 141, DisplayName = "Christian Jacq" },
                new Author { Id = 142, DisplayName = "André Castelot" },
                new Author { Id = 143, DisplayName = "J.M.G.Le Clézio" },
                new Author { Id = 144, DisplayName = "Roberta Rich" },
                new Author { Id = 145, DisplayName = "C.W.Gortner" },
                new Author { Id = 146, DisplayName = "Oliver Bowden" },
                new Author { Id = 147, DisplayName = "Juli Zeh" }
            );
        }
    }
}
